name: Terraform CI/CD Workflow

# Trigger the workflow on pull requests and pushes to the default and custom branch
on:
  pull_request:
    branches:
        - main
  push:
#    branches:
#        - task_2_vasylk # Custom branch
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run the workflow on"
        required: true
        default: "main"

env:
    TERRAFORM_VERSION: ${{ vars.TERRAFORM_VERSION }}
    AWS_DEF_REGION: ${{ vars.AWS_DEF_REGION }}

permissions: 
    id-token: write
    contents: read

jobs:
  terraform-check:
    name: Terraform Check (fmt)
    runs-on: ubuntu-latest

    defaults:
        run:
            working-directory: task_2_dir

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }} 

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
  
    defaults:
        run:
            working-directory: task_2_dir
            
    needs: terraform-check
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }} # Store this in GitHub Secrets
          aws-region: ${{ env.AWS_DEF_REGION }} # Specify your region

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    defaults:
        run:
            working-directory: task_2_dir
            
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/task_1_vasylk'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_DEF_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve